---
title: 'Big data analysis and visualisation: Pre-work'
author: "J.M.T. Roos"
date: "25 April 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Welcome to the [Big data analysis and visualisation course](http://www.egs3h.eur.nl/doctoral-education/phd-course-guide/methodology-courses-and-philosophy-of-science/big-data-analysis-and-visualisation/) offered by the EGS3H. Because we have more material to cover than we have time together, you will need to do a few things before our first meeting.

## Familiarity with R

You should already be *familiar*  with [R programming language](https://www.r-project.org/) (i.e., you do not need to be *proficient* [yet], but you should have had some experience with R in the past). Please see [this page I put together](http://www.jasonmtroos.com/learning-r/) for a list of resources that will help you gain experience using R. 

In particular, you should follow [this tutorial I created for my Marketing Analytics course](http://www.jasonmtroos.com/assets/media/teaching/assignment_1.pdf) prior to the first session.


## Software

You need to have the following two programs installed on whichever laptop you will bring to the course sessions: [git](https://git-scm.com), and [RStudio](https://www.rstudio.com).

#### Git

Git is a program for keeping track of changes you make to your code over time.

Install git on your computer if you do not already have it. You can download git from https://git-scm.com/downloads and find detailed installation instructions at [https://git-scm.com/book/en/v2/Getting-Started-Installing-Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git). 


#### RStudio

RStudio provides an integrated development environment (IDE) for writing and executing scripts written in R.

Install RStudio on your computer if you do not already have it. You can download RStudio from [https://www.rstudio.com/products/rstudio/download/](https://www.rstudio.com/products/rstudio/download/). 

Please note the following: 

* RStudio offers both commercial and free versions; you should install the free version
* Installing RStudio also installs R on your computer, so should not be a need to install R if it is not already installed. If you already have R installed on your computer, you might want to update it to the latest version before installing RStudio 

## GitHub account

We will use [GitHub](https://github.com/) to share code and data. Please sign up for an account at https://github.com/ if you do not already have one.



