---
title: "Course overview"
author: "J.M.T. Roos"
date: "Last updated 4 May 2016"
autosize: false
css: "../css/slides.css"
output: 
  revealjs::revealjs_presentation:
    theme: simple
    highlight: NULL
    transition: slide
    slide_level: 1
    reveal_options:
      controls: false
      margin: .05
    pandoc_args:
      [
      "--variable", "slideNumber='c/t'",
      "--variable", "transitionSpeed=slow",
      "--variable", "viewDistance=5"
      ]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Course abstract
===============
A systematic introduction to issues of collecting, preparing, analyzing, and visualizing so-called 'big data.' 

You will learn how to write, debug, and keep track of your own code using R, a popular programming language for data manipulation, analysis, and visualization. 

Objectives
==========
*	Basic understanding of big data and social media analytics in the context of social science and humanities research
*	Write code in R in order to obtain, prepare, analyze, and visualize data
*	Automate data collection from web sites and social media
*	Basic proficiency with tools for analyzing large quantities of text
*	Monitor and manage the various steps of data collection and analysis for both integrity and replication purposes
*	Become a more productive (taking less time to analyze your data) and careful (making fewer mistakes) scientist

Course structure
=================
* Next four Wednesdays from 13.00 -- 17.00
* Different room each week ([see this page for details](http://www.egs3h.eur.nl/doctoral-education/phd-course-guide/methodology-courses-and-philosophy-of-science/big-data-analysis-and-visualisation/))
* Sessions include a mix of lectures, demonstrations, and/or in-class exercises
* Bring your laptop to every session
    + You **must** have the necessary rights to install software on your laptop
* Ideadlly, you will work with data sets relevant to your reasearch:
    + Experiments, surveys, time series, panels, whatever...
    + I will supply data sets as well


Unlocking achievements
======================
* Attend every session (there will be a sign-in sheet)
* According to the Dutch government, each ECTS credit requires 28 hours of work
* At 2.5 ECTS, that's 70 hours total for the course
    + 17.5 hours per week, including time in class
    + With 4 hours in class each week, 2.5 ECTS implies **13.5 hours per week of work on your own**
* Learning new programming skills takes time, so if you want to get something from this course, 13.5 hours per week represents the **minimum level of effort**


Today's session
=====
## Course overview and first steps with R

* You will create, edit, and compile an R-markdown file that contains both a free text discussion of your data analysis, your code, and any output from that code (including plots).

* We will build an R-markdown file that collects data from an online source, performs a few basic manipulations, and plots the results. You will learn how to use version control software to track changes to this markdown file over time.

Session 2: Acquiring, preparing, and visualising data
====================================================
## 18 May, 13.00 -- 17.00, Mandeville T18--22


* You will learn how to write code to acquire data from files located on the web or stored on your local computer, load them into R, and “clean” the data in preparation for further analysis (such as data visualisation). 

* You will then learn about a powerful yet relatively simple "grammar" for visualising data that has been implemented in the `ggplot2` package in R

* We will also discuss the underlying theory that drives this grammar (including the psychological principles behind effective data visualisation), and gain an appreciation for how visualisation can lead to insights about data more quickly than statistical analysis.

Session 3: Obtaining data from web sites and social media
===================================================
## 25 May, 13.00 -- 17.00, Mandeville T5--85

* You will learn how to acquire data from various online sources, such as web pages and the Twitter API, and how to automation these procedures. 

* You will continue to gain practice preparing, analysing, and visualising these data.

Session 4: Text and sentiment analysis
====================================================
## 1 June, 13.00 -- 17.00, Mandeville T18--42

* You will learn how to process large amounts of unstructured data (e.g. text documents) to extract important features (e.g., the occurrence of special words).

* You will also learn how to conduct automatic sentiment analysis (scoring text based its positivity or negativity).


